# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cad5ba01b4fed613fe354c1532245e33f31360eb7c8ec62fc76fc93b2494e8281235ce5daacc5b5c53427c6cb71ea8f78869d645ae5df7aadf0aec99e881cbe

test:
  secret_key_base: 36cf2103c8036ab36dec3a7237a864fa5ada233edfe1e8e5f5c65a3eb9179a10a98ca86dc22b885e633c64748158c68a97c3ae5bfd795b18ef8900ec0de66032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
